package Corba_DAO;


/**
* Corba_DAO/GioHangsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public final class GioHangsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.GioHang value[] = null;

  public GioHangsHolder ()
  {
  }

  public GioHangsHolder (DTO.GioHang[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.GioHangsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.GioHangsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.GioHangsHelper.type ();
  }

}
