package Corba_DAO;


/**
* Corba_DAO/HoaDonChiTietsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public final class HoaDonChiTietsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.HoaDonChiTiet value[] = null;

  public HoaDonChiTietsHolder ()
  {
  }

  public HoaDonChiTietsHolder (DTO.HoaDonChiTiet[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.HoaDonChiTietsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.HoaDonChiTietsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.HoaDonChiTietsHelper.type ();
  }

}
