package Corba_DAO;


/**
* Corba_DAO/IAccountAdminDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 23, 2019 9:17:11 AM ICT
*/

public interface IAccountAdminDAOOperations 
{
  DTO.AccountAdmin Login (String taiKhoan, String matKhau);
} // interface IAccountAdminDAOOperations
