package Corba_DAO;


/**
* Corba_DAO/IAccountAdminDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public interface IAccountAdminDAOOperations 
{
  DTO.AccountAdmin Login (String taiKhoan, String matKhau);
} // interface IAccountAdminDAOOperations
