package Corba_DAO;


/**
* Corba_DAO/IAccountAdminDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public interface IAccountAdminDAOOperations 
{
  DTO.AccountAdmin Login (String taiKhoan, String matKhau);
} // interface IAccountAdminDAOOperations
