package Corba_DAO;

/**
* Corba_DAO/IDanhMucDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public final class IDanhMucDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba_DAO.IDanhMucDAO value = null;

  public IDanhMucDAOHolder ()
  {
  }

  public IDanhMucDAOHolder (Corba_DAO.IDanhMucDAO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.IDanhMucDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.IDanhMucDAOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.IDanhMucDAOHelper.type ();
  }

}
