package Corba_DAO;


/**
* Corba_DAO/IDanhMucDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public interface IDanhMucDAOOperations 
{
  DTO.DanhMuc[] LayDanhSach ();
  boolean Create (DTO.DanhMuc x);
  boolean Update (DTO.DanhMuc x);
  boolean Delete (int id);
  DTO.DanhMuc[] TimKiem (String search);
  DTO.DanhMuc GetById (int id);
} // interface IDanhMucDAOOperations
