package Corba_DAO;


/**
* Corba_DAO/IDanhMucDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public interface IDanhMucDAOOperations 
{
  DTO.DanhMuc[] LayDanhSach ();
  boolean Create (DTO.DanhMuc x);
  boolean Update (DTO.DanhMuc x);
  boolean Delete (int id);
  DTO.DanhMuc[] TimKiem (String search);
  DTO.DanhMuc GetById (int id);
} // interface IDanhMucDAOOperations
