package Corba_DAO;


/**
* Corba_DAO/IDanhMucDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 9:15:49 PM ICT
*/

public interface IDanhMucDAOOperations 
{
  DTO.DanhMuc[] LayDanhSach ();
  boolean Create (DTO.DanhMuc x);
  boolean Update (DTO.DanhMuc x);
  boolean Delete (int id);
  DTO.DanhMuc[] TimKiem (String search);
} // interface IDanhMucDAOOperations
