package Corba_DAO;


/**
* Corba_DAO/IDanhMucDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public interface IDanhMucDAO extends IDanhMucDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDanhMucDAO
