package Corba_DAO;


/**
* Corba_DAO/IGioHangDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public abstract class IGioHangDAOPOA extends org.omg.PortableServer.Servant
 implements Corba_DAO.IGioHangDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("LayDanhSach", new java.lang.Integer (0));
    _methods.put ("Create", new java.lang.Integer (1));
    _methods.put ("Update", new java.lang.Integer (2));
    _methods.put ("Delete", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba_DAO/IGioHangDAO/LayDanhSach
       {
         int idKhachHang = in.read_long ();
         DTO.GioHang $result[] = null;
         $result = this.LayDanhSach (idKhachHang);
         out = $rh.createReply();
         Corba_DAO.GioHangsHelper.write (out, $result);
         break;
       }

       case 1:  // Corba_DAO/IGioHangDAO/Create
       {
         DTO.GioHang x = DTO.GioHangHelper.read (in);
         boolean $result = false;
         $result = this.Create (x);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Corba_DAO/IGioHangDAO/Update
       {
         DTO.GioHang x = DTO.GioHangHelper.read (in);
         boolean $result = false;
         $result = this.Update (x);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Corba_DAO/IGioHangDAO/Delete
       {
         int idKhachHang = in.read_long ();
         int maSP = in.read_long ();
         boolean $result = false;
         $result = this.Delete (idKhachHang, maSP);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba_DAO/IGioHangDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IGioHangDAO _this() 
  {
    return IGioHangDAOHelper.narrow(
    super._this_object());
  }

  public IGioHangDAO _this(org.omg.CORBA.ORB orb) 
  {
    return IGioHangDAOHelper.narrow(
    super._this_object(orb));
  }


} // class IGioHangDAOPOA
