package Corba_DAO;


/**
* Corba_DAO/IGioHangDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public interface IGioHangDAOOperations 
{
  DTO.GioHang[] LayDanhSach (int idKhachHang);
  boolean Create (DTO.GioHang x);
  boolean Update (DTO.GioHang x);
  boolean Delete (int idKhachHang, int maSP);
} // interface IGioHangDAOOperations
