package Corba_DAO;


/**
* Corba_DAO/IGioHangDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public interface IGioHangDAOOperations 
{
  DTO.GioHang[] LayDanhSach (int idKhachHang);
  boolean Create (DTO.GioHang x);
  boolean Update (DTO.GioHang x);
  boolean Delete (int idKhachHang, int maSP);
} // interface IGioHangDAOOperations
