package Corba_DAO;


/**
* Corba_DAO/IHoaDonDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public interface IHoaDonDAOOperations 
{
  DTO.HoaDon[] LayDanhSach ();
  boolean Create (DTO.HoaDon x);
  boolean Update (DTO.HoaDon x);
  boolean ThanhToan (int id);
  DTO.HoaDon[] TimKiem (String date);
} // interface IHoaDonDAOOperations
