package Corba_DAO;


/**
* Corba_DAO/IHoaDonChiTietDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public interface IHoaDonChiTietDAOOperations 
{
  DTO.HoaDonChiTiet[] LayDanhSachHoaDonChiTiet (int idHoaDon);
} // interface IHoaDonChiTietDAOOperations
