package Corba_DAO;


/**
* Corba_DAO/IHoaDonDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public interface IHoaDonDAO extends IHoaDonDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IHoaDonDAO
