package Corba_DAO;


/**
* Corba_DAO/IHoaDonChiTietDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public interface IHoaDonChiTietDAOOperations 
{
  DTO.HoaDonChiTiet[] LayDanhSachHoaDonChiTiet (int idHoaDon);
} // interface IHoaDonChiTietDAOOperations
