package Corba_DAO;


/**
* Corba_DAO/IHoaDonDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public interface IHoaDonDAOOperations 
{
  DTO.HoaDon[] LayDanhSach ();
  boolean Create (DTO.HoaDon x);
  boolean Update (DTO.HoaDon x);
  boolean ThanhToan (int id);
  DTO.HoaDon[] TimKiem (String date);
} // interface IHoaDonDAOOperations
