package Corba_DAO;


/**
* Corba_DAO/IHoaDonChiTietDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 23, 2019 9:17:11 AM ICT
*/

public interface IHoaDonChiTietDAOOperations 
{
  DTO.HoaDonChiTiet[] LayDanhSachHoaDonChiTiet (int idHoaDon);
} // interface IHoaDonChiTietDAOOperations
