package Corba_DAO;


/**
* Corba_DAO/IKhachHangDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 23, 2019 9:17:11 AM ICT
*/

public interface IKhachHangDAOOperations 
{
  DTO.KhachHang[] LayDanhSach ();
  boolean Create (DTO.KhachHang x);
  boolean Update (DTO.KhachHang x);
  boolean Delete (int id);
  DTO.KhachHang[] TimKiem (String search);
  DTO.KhachHang GetById (int id);
} // interface IKhachHangDAOOperations
