package Corba_DAO;


/**
* Corba_DAO/IKhachHangDAOPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public abstract class IKhachHangDAOPOA extends org.omg.PortableServer.Servant
 implements Corba_DAO.IKhachHangDAOOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("LayDanhSach", new java.lang.Integer (0));
    _methods.put ("Create", new java.lang.Integer (1));
    _methods.put ("Update", new java.lang.Integer (2));
    _methods.put ("UpdateInfo", new java.lang.Integer (3));
    _methods.put ("Delete", new java.lang.Integer (4));
    _methods.put ("TimKiem", new java.lang.Integer (5));
    _methods.put ("GetById", new java.lang.Integer (6));
    _methods.put ("Login", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba_DAO/IKhachHangDAO/LayDanhSach
       {
         DTO.KhachHang $result[] = null;
         $result = this.LayDanhSach ();
         out = $rh.createReply();
         Corba_DAO.KhachHangsHelper.write (out, $result);
         break;
       }

       case 1:  // Corba_DAO/IKhachHangDAO/Create
       {
         DTO.KhachHang x = DTO.KhachHangHelper.read (in);
         boolean $result = false;
         $result = this.Create (x);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Corba_DAO/IKhachHangDAO/Update
       {
         DTO.KhachHang x = DTO.KhachHangHelper.read (in);
         boolean $result = false;
         $result = this.Update (x);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Corba_DAO/IKhachHangDAO/UpdateInfo
       {
         int id = in.read_long ();
         String hoTen = in.read_string ();
         String soDienThoai = in.read_string ();
         String diaChi = in.read_string ();
         boolean $result = false;
         $result = this.UpdateInfo (id, hoTen, soDienThoai, diaChi);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // Corba_DAO/IKhachHangDAO/Delete
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.Delete (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // Corba_DAO/IKhachHangDAO/TimKiem
       {
         String search = in.read_string ();
         DTO.KhachHang $result[] = null;
         $result = this.TimKiem (search);
         out = $rh.createReply();
         Corba_DAO.KhachHangsHelper.write (out, $result);
         break;
       }

       case 6:  // Corba_DAO/IKhachHangDAO/GetById
       {
         int id = in.read_long ();
         DTO.KhachHang $result = null;
         $result = this.GetById (id);
         out = $rh.createReply();
         DTO.KhachHangHelper.write (out, $result);
         break;
       }

       case 7:  // Corba_DAO/IKhachHangDAO/Login
       {
         String email = in.read_string ();
         String matKhau = in.read_string ();
         DTO.KhachHang $result = null;
         $result = this.Login (email, matKhau);
         out = $rh.createReply();
         DTO.KhachHangHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba_DAO/IKhachHangDAO:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IKhachHangDAO _this() 
  {
    return IKhachHangDAOHelper.narrow(
    super._this_object());
  }

  public IKhachHangDAO _this(org.omg.CORBA.ORB orb) 
  {
    return IKhachHangDAOHelper.narrow(
    super._this_object(orb));
  }


} // class IKhachHangDAOPOA
