package Corba_DAO;


/**
* Corba_DAO/IKhachHangDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Wednesday, November 20, 2019 12:59:50 PM ICT
*/

public interface IKhachHangDAO extends IKhachHangDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IKhachHangDAO
