package Corba_DAO;


/**
* Corba_DAO/IKhachHangDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 4:26:39 PM ICT
*/

public interface IKhachHangDAOOperations 
{
  DTO.KhachHang[] LayDanhSach ();
  boolean Create (DTO.KhachHang x);
  boolean Update (DTO.KhachHang x);
  boolean Delete (int id);
  DTO.KhachHang TimKiem (String search);
} // interface IKhachHangDAOOperations
