package Corba_DAO;


/**
* Corba_DAO/ILoaiSanPhamDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public interface ILoaiSanPhamDAO extends ILoaiSanPhamDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ILoaiSanPhamDAO
