package Corba_DAO;


/**
* Corba_DAO/ILoaiSanPhamDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public interface ILoaiSanPhamDAOOperations 
{
  DTO.LoaiSanPham[] LayDanhSach ();
  boolean Create (DTO.LoaiSanPham x);
  boolean Update (DTO.LoaiSanPham x);
  boolean Delete (int id);
  DTO.LoaiSanPham[] TimKiem (String search);
  DTO.LoaiSanPham GetById (int id);
  DTO.LoaiSanPham[] LayDanhSachTheoDanhMuc (int id);
} // interface ILoaiSanPhamDAOOperations
