package Corba_DAO;

/**
* Corba_DAO/ILoaiSanPhamDAOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 9:15:49 PM ICT
*/

public final class ILoaiSanPhamDAOHolder implements org.omg.CORBA.portable.Streamable
{
  public Corba_DAO.ILoaiSanPhamDAO value = null;

  public ILoaiSanPhamDAOHolder ()
  {
  }

  public ILoaiSanPhamDAOHolder (Corba_DAO.ILoaiSanPhamDAO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.ILoaiSanPhamDAOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.ILoaiSanPhamDAOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.ILoaiSanPhamDAOHelper.type ();
  }

}
