package Corba_DAO;


/**
* Corba_DAO/ILoaiSanPhamDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public interface ILoaiSanPhamDAO extends ILoaiSanPhamDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ILoaiSanPhamDAO
