package Corba_DAO;


/**
* Corba_DAO/INhaCungCapDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 9:15:49 PM ICT
*/

public interface INhaCungCapDAO extends INhaCungCapDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface INhaCungCapDAO
