package Corba_DAO;


/**
* Corba_DAO/INhaSanXuatDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 4:26:39 PM ICT
*/

public interface INhaSanXuatDAO extends INhaSanXuatDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface INhaSanXuatDAO
