package Corba_DAO;


/**
* Corba_DAO/INhaCungCapDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public interface INhaCungCapDAOOperations 
{
  DTO.NhaCungCap[] LayDanhSach ();
  boolean Create (DTO.NhaCungCap x);
  boolean Update (DTO.NhaCungCap x);
  boolean Delete (int id);
  DTO.NhaCungCap[] TimKiem (String search);
  DTO.NhaCungCap GetById (int id);
} // interface INhaCungCapDAOOperations
