package Corba_DAO;


/**
* Corba_DAO/IPhieuNhapDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 5:29:00 PM ICT
*/

public interface IPhieuNhapDAO extends IPhieuNhapDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPhieuNhapDAO
