package Corba_DAO;


/**
* Corba_DAO/IPhieuNhapDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public interface IPhieuNhapDAOOperations 
{
  DTO.PhieuNhap[] LayDanhSach ();
  boolean Create (DTO.PhieuNhap x);
  boolean Update (int id, String ngayNhap);
  boolean Delete (int id);
  DTO.PhieuNhap[] TimKiem (String date);
  DTO.PhieuNhap GetPhieuNhapCuoiCung ();
} // interface IPhieuNhapDAOOperations
