package Corba_DAO;


/**
* Corba_DAO/IPhieuNhapDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public interface IPhieuNhapDAO extends IPhieuNhapDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPhieuNhapDAO
