package Corba_DAO;


/**
* Corba_DAO/ISanPhamDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Wednesday, November 20, 2019 12:59:50 PM ICT
*/

public interface ISanPhamDAOOperations 
{
  DTO.SanPham[] LayDanhSach ();
  boolean Create (DTO.SanPham x);
  boolean Update (DTO.SanPham x);
  boolean Delete (int id);
  DTO.SanPham TimKiem (String search);
} // interface ISanPhamDAOOperations
