package Corba_DAO;


/**
* Corba_DAO/ISanPhamDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public interface ISanPhamDAOOperations 
{
  DTO.SanPham[] LayDanhSach ();
  boolean Create (DTO.SanPham x);
  boolean Update (DTO.SanPham x);
  boolean Delete (int id);
  DTO.SanPham[] TimKiem (String search);
  DTO.SanPham GetById (int id);
  void UpdateStatus (int id);
  DTO.SanPham[] GetListSanPhamMoiNhat ();
  DTO.SanPham[] GetListSanPhamTimKiem (String search);
  DTO.SanPham[] GetListSanPhamTheoLoaiSanPham (int id);
} // interface ISanPhamDAOOperations
