package Corba_DAO;


/**
* Corba_DAO/ISanPhamDAO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public interface ISanPhamDAO extends ISanPhamDAOOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ISanPhamDAO
