package Corba_DAO;


/**
* Corba_DAO/ISanPhamDAOOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 30, 2019 3:53:39 PM ICT
*/

public interface ISanPhamDAOOperations 
{
  DTO.SanPham[] LayDanhSach ();
  boolean Create (DTO.SanPham x);
  boolean Update (DTO.SanPham x);
  boolean Delete (int id);
  DTO.SanPham[] TimKiem (String search);
} // interface ISanPhamDAOOperations
