package Corba_DAO;


/**
* Corba_DAO/LoaiSanPhamsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public final class LoaiSanPhamsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.LoaiSanPham value[] = null;

  public LoaiSanPhamsHolder ()
  {
  }

  public LoaiSanPhamsHolder (DTO.LoaiSanPham[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.LoaiSanPhamsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.LoaiSanPhamsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.LoaiSanPhamsHelper.type ();
  }

}
