package Corba_DAO;


/**
* Corba_DAO/NhaCungCapsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public final class NhaCungCapsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.NhaCungCap value[] = null;

  public NhaCungCapsHolder ()
  {
  }

  public NhaCungCapsHolder (DTO.NhaCungCap[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.NhaCungCapsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.NhaCungCapsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.NhaCungCapsHelper.type ();
  }

}
