package Corba_DAO;


/**
* Corba_DAO/PhieuNhapsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Saturday, November 23, 2019 9:17:11 AM ICT
*/

public final class PhieuNhapsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.PhieuNhap value[] = null;

  public PhieuNhapsHolder ()
  {
  }

  public PhieuNhapsHolder (DTO.PhieuNhap[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.PhieuNhapsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.PhieuNhapsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.PhieuNhapsHelper.type ();
  }

}
