package Corba_DAO;


/**
* Corba_DAO/PhieuNhapChiTietsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 9:15:49 PM ICT
*/

abstract public class PhieuNhapChiTietsHelper
{
  private static String  _id = "IDL:Corba_DAO/PhieuNhapChiTiets:1.0";

  public static void insert (org.omg.CORBA.Any a, DTO.PhieuNhapChiTiet[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DTO.PhieuNhapChiTiet[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DTO.PhieuNhapChiTietHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Corba_DAO.PhieuNhapChiTietsHelper.id (), "PhieuNhapChiTiets", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DTO.PhieuNhapChiTiet[] read (org.omg.CORBA.portable.InputStream istream)
  {
    DTO.PhieuNhapChiTiet value[] = null;
    int _len0 = istream.read_long ();
    value = new DTO.PhieuNhapChiTiet[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = DTO.PhieuNhapChiTietHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DTO.PhieuNhapChiTiet[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      DTO.PhieuNhapChiTietHelper.write (ostream, value[_i0]);
  }

}
