package Corba_DAO;


/**
* Corba_DAO/PhieuNhapChiTietsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public final class PhieuNhapChiTietsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.PhieuNhapChiTiet value[] = null;

  public PhieuNhapChiTietsHolder ()
  {
  }

  public PhieuNhapChiTietsHolder (DTO.PhieuNhapChiTiet[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.PhieuNhapChiTietsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.PhieuNhapChiTietsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.PhieuNhapChiTietsHelper.type ();
  }

}
