package Corba_DAO;


/**
* Corba_DAO/SanPhamsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public final class SanPhamsHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.SanPham value[] = null;

  public SanPhamsHolder ()
  {
  }

  public SanPhamsHolder (DTO.SanPham[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Corba_DAO.SanPhamsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Corba_DAO.SanPhamsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Corba_DAO.SanPhamsHelper.type ();
  }

}
