module DTO
{
    struct AccountAdmin
    {
        long id;
        string taiKhoan;
        string matKhau;
    };
    
    struct NhaSanXuat
    {
        long maNSX;
        string tenNSX;
        string thongTin;
        string logo;
    };

    struct NhaCungCap
    {
        long maNCC;
        string tenNCC;
        string diaChi;
        string soDT;
        string email;
    };

    struct DanhMuc
    {
        long maDanhMuc;
        string tenDanhMuc;
    };
    
    struct LoaiSanPham
    {
        long maLoaiSP;
        string tenLoai;
        long maDanhMuc;
        string tenDanhMuc;
    };

    struct SanPham
    {
        long maSP;
        string tenSP;
        float donGia;
        string ngayCapNhat;
        string moTa;
        string hinhAnh;
        long soLuongTon;
        long maNCC;
        long maNSX;
        long maLoaiSP;
        boolean trangThai;
    };
    
    struct KhachHang
    {
        long id;
        string email;
        string matKhau;
        string hoTen;
        string diaChi;
        string soDT;
    };

    struct HoaDon
    {
        long maHD;
        string ngayDat;
        long idKhachHang;
        float tongTien;
        boolean daThanhToan;
        string tenKhachHang;
    };

    struct HoaDonChiTiet
    {
        long maHD;
        long maSP;
        long soLuongMua;
        float donGia;
        string tenSP;
    };

    struct PhieuNhap
    {
        long maPN;
        string ngayNhap;
        float tongTienNhap;
    };

    struct PhieuNhapChiTiet
    {
        long maPN;
        long maSP;
        long soLuongNhap;
        float donGiaNhap;
        string tenSP;
    };

    struct GioHang
    {
        long id;
        long idKhachHang;
        long maSP;
        long soLuongDat;
        boolean trangThai;
        string tenSP;
    };
};

module Corba_DAO
{
    typedef sequence<DTO::HoaDon> HoaDons;
    typedef sequence<DTO::DanhMuc> DanhMucDAOs;
    typedef sequence<DTO::HoaDonChiTiet> HoaDonChiTiets;
    typedef sequence<DTO::KhachHang> KhachHangs;
    typedef sequence<DTO::LoaiSanPham> LoaiSanPhams;
    typedef sequence<DTO::NhaCungCap> NhaCungCaps;
    typedef sequence<DTO::NhaSanXuat> NhaSanXuats;
    typedef sequence<DTO::PhieuNhap> PhieuNhaps;
    typedef sequence<DTO::PhieuNhapChiTiet> PhieuNhapChiTiets;
    typedef sequence<DTO::SanPham> SanPhams;
    typedef sequence<DTO::GioHang> GioHangs;

    interface IAccountAdminDAO
    {
        DTO::AccountAdmin Login(in string taiKhoan, in string matKhau);
    };

    interface IDanhMucDAO
    {
        DanhMucDAOs LayDanhSach();
        boolean Create(in DTO::DanhMuc x);
        boolean Update(in DTO::DanhMuc x);
        boolean Delete(in long id);
        DanhMucDAOs TimKiem(in string search);
        DTO::DanhMuc GetById(in long id);
    };

    interface IHoaDonChiTietDAO
    {
        HoaDonChiTiets LayDanhSachHoaDonChiTiet(in long idHoaDon);
    };
    
    interface IHoaDonDAO
    {
        HoaDons LayDanhSach();
        boolean Create(in DTO::HoaDon x);
        boolean Update(in DTO::HoaDon x);
        boolean ThanhToan(in long id);
        HoaDons TimKiem(in string date);
    };
    
    interface IKhachHangDAO
    {
        KhachHangs LayDanhSach();
        boolean Create(in DTO::KhachHang x);
        boolean Update(in DTO::KhachHang x);
        boolean UpdateInfo(in long id, in string hoTen, in string soDienThoai, in string diaChi);
        boolean Delete(in long id);
        KhachHangs TimKiem(in string search);
        DTO::KhachHang GetById(in long id);
        DTO::KhachHang Login(in string email, in string matKhau);
    };

    interface INhaCungCapDAO
    {
        NhaCungCaps LayDanhSach();
        boolean Create(in DTO::NhaCungCap x);
        boolean Update(in DTO::NhaCungCap x);
        boolean Delete(in long id);
        NhaCungCaps TimKiem(in string search);
        DTO::NhaCungCap GetById(in long id);
    };

    interface INhaSanXuatDAO
    {
        NhaSanXuats LayDanhSach();
        boolean Create(in DTO::NhaSanXuat x);
        boolean Update(in DTO::NhaSanXuat x);
        boolean Delete(in long id);
        boolean UpdateInfo(in long id, in string tenNSX, in string thongTin);
        NhaSanXuats TimKiem(in string search);
        DTO::NhaSanXuat GetById(in long id);
    };

    interface ILoaiSanPhamDAO
    {
        LoaiSanPhams LayDanhSach();
        boolean Create(in DTO::LoaiSanPham x);
        boolean Update(in DTO::LoaiSanPham x);
        boolean Delete(in long id);
        LoaiSanPhams TimKiem(in string search);
        DTO::LoaiSanPham GetById(in long id);
        LoaiSanPhams LayDanhSachTheoDanhMuc(in long id);
    };

    interface ISanPhamDAO
    {
        SanPhams LayDanhSach();
        boolean Create(in DTO::SanPham x);
        boolean Update(in DTO::SanPham x);
        boolean Delete(in long id);
        SanPhams TimKiem(in string search);
        DTO::SanPham GetById(in long id);
        void UpdateStatus(in long id);
        SanPhams GetListSanPhamMoiNhat();
        SanPhams GetListSanPhamTimKiem(in string search);
        SanPhams GetListSanPhamTheoLoaiSanPham(in long id);
    };

    interface IPhieuNhapChiTietDAO
    {
        PhieuNhapChiTiets LayDanhSach(in long idPhieuNhap);
        boolean Create(in DTO::PhieuNhapChiTiet x);
        boolean Update(in DTO::PhieuNhapChiTiet x);
        boolean Delete(in long maPhieuNhap, in long maSP);
        DTO::PhieuNhapChiTiet GetById(in long id);
    };

    interface IPhieuNhapDAO
    {
        PhieuNhaps LayDanhSach();
        boolean Create(in DTO::PhieuNhap x);
        boolean Update(in long id, in string ngayNhap);
        boolean Delete(in long id);
        PhieuNhaps TimKiem(in string date);
        DTO::PhieuNhap GetPhieuNhapCuoiCung();
    };

    interface IGioHangDAO
    {
        GioHangs LayDanhSach(in long idKhachHang);
        boolean Create(in DTO::GioHang x);
        boolean Update(in DTO::GioHang x);
        boolean Delete(in long idKhachHang, in long maSP);
        long GetSoLuongSanPhamTrongGioTheoKhachHang(in long id);
        float GetTongTienSanPhamTrongGioTheoKhachHang(in long id);
    };
};
