package DTO;


/**
* DTO/AccountAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public final class AccountAdmin implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String taiKhoan = null;
  public String matKhau = null;

  public AccountAdmin ()
  {
  } // ctor

  public AccountAdmin (int _id, String _taiKhoan, String _matKhau)
  {
    id = _id;
    taiKhoan = _taiKhoan;
    matKhau = _matKhau;
  } // ctor

} // class AccountAdmin
