package DTO;

/**
* DTO/AccountAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public final class AccountAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.AccountAdmin value = null;

  public AccountAdminHolder ()
  {
  }

  public AccountAdminHolder (DTO.AccountAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DTO.AccountAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DTO.AccountAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DTO.AccountAdminHelper.type ();
  }

}
