package DTO;


/**
* DTO/DanhMuc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public final class DanhMuc implements org.omg.CORBA.portable.IDLEntity
{
  public int maDanhMuc = (int)0;
  public String tenDanhMuc = null;

  public DanhMuc ()
  {
  } // ctor

  public DanhMuc (int _maDanhMuc, String _tenDanhMuc)
  {
    maDanhMuc = _maDanhMuc;
    tenDanhMuc = _tenDanhMuc;
  } // ctor

} // class DanhMuc
