package DTO;

/**
* DTO/GioHangHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 28, 2019 5:56:13 PM ICT
*/

public final class GioHangHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.GioHang value = null;

  public GioHangHolder ()
  {
  }

  public GioHangHolder (DTO.GioHang initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DTO.GioHangHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DTO.GioHangHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DTO.GioHangHelper.type ();
  }

}
