package DTO;


/**
* DTO/GioHang.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 6:05:05 PM ICT
*/

public final class GioHang implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int idKhachHang = (int)0;
  public int maSP = (int)0;
  public int soLuongDat = (int)0;
  public boolean trangThai = false;
  public String tenSP = null;

  public GioHang ()
  {
  } // ctor

  public GioHang (int _id, int _idKhachHang, int _maSP, int _soLuongDat, boolean _trangThai, String _tenSP)
  {
    id = _id;
    idKhachHang = _idKhachHang;
    maSP = _maSP;
    soLuongDat = _soLuongDat;
    trangThai = _trangThai;
    tenSP = _tenSP;
  } // ctor

} // class GioHang
