package DTO;


/**
* DTO/HoaDon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 9:15:49 PM ICT
*/

public final class HoaDon implements org.omg.CORBA.portable.IDLEntity
{
  public int maHD = (int)0;
  public String ngayDat = null;
  public int idKhachHang = (int)0;
  public float tongTien = (float)0;
  public boolean daThanhToan = false;

  public HoaDon ()
  {
  } // ctor

  public HoaDon (int _maHD, String _ngayDat, int _idKhachHang, float _tongTien, boolean _daThanhToan)
  {
    maHD = _maHD;
    ngayDat = _ngayDat;
    idKhachHang = _idKhachHang;
    tongTien = _tongTien;
    daThanhToan = _daThanhToan;
  } // ctor

} // class HoaDon
