package DTO;


/**
* DTO/HoaDonChiTiet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Tuesday, December 3, 2019 10:57:14 PM ICT
*/

public final class HoaDonChiTiet implements org.omg.CORBA.portable.IDLEntity
{
  public int maHD = (int)0;
  public int maSP = (int)0;
  public int soLuongMua = (int)0;
  public float donGia = (float)0;
  public String tenSP = null;

  public HoaDonChiTiet ()
  {
  } // ctor

  public HoaDonChiTiet (int _maHD, int _maSP, int _soLuongMua, float _donGia, String _tenSP)
  {
    maHD = _maHD;
    maSP = _maSP;
    soLuongMua = _soLuongMua;
    donGia = _donGia;
    tenSP = _tenSP;
  } // ctor

} // class HoaDonChiTiet
