package DTO;


/**
* DTO/HoaDonChiTiet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Thursday, November 21, 2019 4:26:39 PM ICT
*/

public final class HoaDonChiTiet implements org.omg.CORBA.portable.IDLEntity
{
  public int maHD = (int)0;
  public int maSP = (int)0;
  public int soLuongMua = (int)0;
  public float donGia = (float)0;

  public HoaDonChiTiet ()
  {
  } // ctor

  public HoaDonChiTiet (int _maHD, int _maSP, int _soLuongMua, float _donGia)
  {
    maHD = _maHD;
    maSP = _maSP;
    soLuongMua = _soLuongMua;
    donGia = _donGia;
  } // ctor

} // class HoaDonChiTiet
