package DTO;


/**
* DTO/KhachHang.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public final class KhachHang implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String email = null;
  public String matKhau = null;
  public String hoTen = null;
  public String diaChi = null;
  public String soDT = null;

  public KhachHang ()
  {
  } // ctor

  public KhachHang (int _id, String _email, String _matKhau, String _hoTen, String _diaChi, String _soDT)
  {
    id = _id;
    email = _email;
    matKhau = _matKhau;
    hoTen = _hoTen;
    diaChi = _diaChi;
    soDT = _soDT;
  } // ctor

    public KhachHang(String Email, String MatKhau, String HoTen, String DiaChi, String SoDT) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

} // class KhachHang
