package DTO;


/**
* DTO/LoaiSanPham.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Monday, November 25, 2019 9:02:18 AM ICT
*/

public final class LoaiSanPham implements org.omg.CORBA.portable.IDLEntity
{
  public int maLoaiSP = (int)0;
  public String tenLoai = null;
  public int maDanhMuc = (int)0;

  public LoaiSanPham ()
  {
  } // ctor

  public LoaiSanPham (int _maLoaiSP, String _tenLoai, int _maDanhMuc)
  {
    maLoaiSP = _maLoaiSP;
    tenLoai = _tenLoai;
    maDanhMuc = _maDanhMuc;
  } // ctor

} // class LoaiSanPham
