package DTO;


/**
* DTO/LoaiSanPham.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public final class LoaiSanPham implements org.omg.CORBA.portable.IDLEntity
{
  public int maLoaiSP = (int)0;
  public String tenLoai = null;
  public int maDanhMuc = (int)0;
  public String tenDanhMuc = null;

  public LoaiSanPham ()
  {
  } // ctor

  public LoaiSanPham (int _maLoaiSP, String _tenLoai, int _maDanhMuc, String _tenDanhMuc)
  {
    maLoaiSP = _maLoaiSP;
    tenLoai = _tenLoai;
    maDanhMuc = _maDanhMuc;
    tenDanhMuc = _tenDanhMuc;
  } // ctor

} // class LoaiSanPham
