package DTO;

/**
* DTO/NhaSanXuatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Wednesday, November 20, 2019 12:59:50 PM ICT
*/

public final class NhaSanXuatHolder implements org.omg.CORBA.portable.Streamable
{
  public DTO.NhaSanXuat value = null;

  public NhaSanXuatHolder ()
  {
  }

  public NhaSanXuatHolder (DTO.NhaSanXuat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DTO.NhaSanXuatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DTO.NhaSanXuatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DTO.NhaSanXuatHelper.type ();
  }

}
