package DTO;


/**
* DTO/PhieuNhapChiTiet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public final class PhieuNhapChiTiet implements org.omg.CORBA.portable.IDLEntity
{
  public int maPN = (int)0;
  public int maSP = (int)0;
  public int soLuongNhap = (int)0;
  public float donGiaNhap = (float)0;
  public String tenSP = null;

  public PhieuNhapChiTiet ()
  {
  } // ctor

  public PhieuNhapChiTiet (int _maPN, int _maSP, int _soLuongNhap, float _donGiaNhap, String _tenSP)
  {
    maPN = _maPN;
    maSP = _maSP;
    soLuongNhap = _soLuongNhap;
    donGiaNhap = _donGiaNhap;
    tenSP = _tenSP;
  } // ctor

} // class PhieuNhapChiTiet
