package DTO;


/**
* DTO/PhieuNhap.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Model.idl
* Sunday, December 1, 2019 2:33:34 PM ICT
*/

public final class PhieuNhap implements org.omg.CORBA.portable.IDLEntity
{
  public int maPN = (int)0;
  public String ngayNhap = null;
  public float tongTienNhap = (float)0;

  public PhieuNhap ()
  {
  } // ctor

  public PhieuNhap (int _maPN, String _ngayNhap, float _tongTienNhap)
  {
    maPN = _maPN;
    ngayNhap = _ngayNhap;
    tongTienNhap = _tongTienNhap;
  } // ctor

} // class PhieuNhap
